const ItalianObjects = {
"person":"persona",
"bicycle": "bicicletta",
"car" : "automobile",
"motorbike": "motocicletta",
"aeroplane" : "aereoplano",
"bus" : "autobus",
"train" : "treno",
"truck" : "autocarro",
"boat" : "barca",
"traffic light" : "semaforo",
"fire hydrant" : "estintore",
"stop sign" : "segnale di stop",
"parking meter" : "parchimetro",
"bench" : "panchina",
"bird" : "uccello",
"cat" : "gatto",
"dog" : "cane",
"horse" : "cavallo",
"sheep" : "pecora",
"cow" : "mucca",
"elephant" : "elefante",
"bear" : "orso",
"zebra" : "zebra",
"giraffe": "giraffa",
"backpack" : "zaino",
"umbrella" : "ombrello",
"handbag" : "borsa",
"tie" : "cravatta",
"suitcase" : "valigia",
"frisbee" : "frisbi",
"skis" : "sci",
"snowboard" : "snowboard",
"sports ball" : "pallone",
"kite" : "deltaplano",
"baseball bat" : "mazza da baseball",
"baseball glove" : "guanto da baseball",
"skateboard" : "skateboard",
"surfboard": "tavola da surf",
"tennis racket": "racchetta da tennis",
"bottle" : "bottiglia",
"wine glass" : "bicchiere di vino",
"cup" : "tazza",
"fork" : "forchetta",
"knife" : "coltello",
"spoon" : "cucchiaio",
"bowl" : "ciotola",
"banana" : "banana",
"apple" : "mela",
"sandwich" : "panino",
"orange" : "arancia",
"broccoli" : "broccoli",
"carrot" : "carota",
"hot dog" : "hot dog",
"pizza" : "pizza",
"donut": "ciambella",
"cake" : "torta",
"chair" : "sedia",
"sofa" : "divano",
"pottedplant" : "piantina",
"bed" : "letto",
"diningtable" : "tavolo",
"toilet" : "bagno",
"tvmonitor" : "monitor",
"laptop" : "computer portatile",
"mouse" : "mouse",
"remote" : "telecomando",
"keyboard" : "tastiera",
"cell phone" : "telefono",
"microwave" : "forno a microonde",
"oven" : "forno elettrico",
"toaster" : "tostapane",
"sink" : "lavandino",
"refrigerator" : "frigorifero",
"book" : "libro",
"clock" : "orologio",
"vase" : "vaso",
"scissors" : "forbici",
"teddy bear" : "peluche",
"hair drier" : "asciugacapelli",
"toothbrush" : "spazzolino"
};

List<String> dangElements = [
  'bicycle',
  'car',
  'motorbike',
  'bus',
  'train',
  'truck',
  'traffic light',
  'stop sign',
  'laptop'
];
